### ISSUE TITLE
Marshmallow Support

### ISSUE THREAD

**Issue by timea-techgirl** [liuzhushaonian/Lin15#3]
Can you please add marshmallow support?
I can help with translating to English.

**Comment by liuzhushaonian** [comment]
I don't think it's necessary to adapt this on marshmallows, because the xposed module of XQS Background supports marshmallow, and the background function of lin15 is to refer to it. So if you want to use this feature on marshmallows, go to the XQS Background module. Regarding translation into English, I have implemented it through Google Translate. If you want to make more user-friendly localization, then you are welcome to help. The app completely puts the text in the xml file, if you can translate it more Ok, that would be great.

**Comment by timea-techgirl** [comment]
Sure, thanks.

**Comment by timea-techgirl** [comment]
Sorry, now I remembered why I requested marshmallow support. Your app supports blurring. Xqs background doesn't have blurring. :(

**Comment by liuzhushaonian** [comment]
Regarding Gaussian Blur, it is just a matter of rendering a normal image into a Gaussian blur and adding it. There aren't many people using this feature, at least for me, and very few people use it.
